### ISSUE TITLE
HTML code in "Exclude classes" causing crashes

### ISSUE THREAD

**Issue by canha42** [canha42/pinterest-pin-it#11]
Sometimes HTML code is added to the "exclude classes" window, causing multiple errors.

Solution: sanitize field.

Source:
http://wordpress.org/support/topic/plugin-pinterest-pin-it-button-for-images-warning

**Comment by vhf** [comment]
TODO :
1. `htmlspecialchars(strip_tags($input))` on exclude classes input
2. In the function failing here (`ppibfi_pinterest.php:189`), check generated PCRE with `FILTER_VALIDATE_REGEXP`, and fail silently if PCRE doesn't validate
3. Improve explaination on admin interface on how to use the field "exclude classes" for non-tech guys

Expect this part for the end of week as well.

**Comment by canha42** [comment]
The plugin seems to be generating an error when installed in some cases. Something starting with a <br />. Maybe the function xc_pin_intstall() has something wrong with it when it tries to run the update_option on pibfi_NoShowButton?

Btw, please add these changes to the master branch as I intend to roll out only these changes (not the 1.1 changes yet)

**Comment by vhf** [comment]
1/ Yep, xc_pin_intstall() was wrong. Problem was : `if(get_option('haha')) != false) {`.
2/ Exclude classes should not crash anything anymore. I also sanitized every other input, as it was very XSS unsafe before. Next step (reminder : create an issue) : use nonces.

**Comment by canha42** [comment]
Changed milestone to 1.1
