### ISSUE TITLE
Button shouldn't show on all images

### ISSUE THREAD

**Issue by canha42** [canha42/pinterest-pin-it#12]
Some plugins don't add classes to the images, causing the Pin It button to show on them (such as social media icons).

Solution:
Ignore smaller images - user can set up this size.

Source:
http://wordpress.org/support/topic/plugin-pinterest-pin-it-button-for-images-social-icon-issues-as-well-and-suggestion

**Comment by vhf** [comment]
Not a solution IMO. Getting the size of every single image of a post on every visit is feasible but not reasonable.

Consider a blog with cheap hosting, 3 pictures in a post with 10 smileys and a few other theme pictures. Pinterest pin it will slow it down as hell. It's supposed to be a "light" plugin.

WP adds automatically some classes (`attachment-thumbnail`, `wp-post-image`) to the images inserted in a post, why not using them ? I'll try something on friday.

**Comment by vhf** [comment]
Sorry, took a good look at the code and reached following conclusion : fixing this on 1.0.2 makes no sense.
A lot of rewrite is needed, and it would not be careful nor realistic to do it, test it and release it in 2-3 days. I suggest releasing 1.0.2 with Issue11 fixed very soon (i.e. this week-end) and jump on the occasion to announce the release of 1.1 in two weeks time. People will be looking forward to 1.1 and it will soon be ready.

**Comment by vhf** [comment]
Changed milestone to 1.1.

Fixed in 1.1.

Please test and close ticket if ok.

**Comment by canha42** [comment]
Tested and working. Available in 1.1. Thanks!
