### ISSUE TITLE
Incompatible with the Social Sharing Toolkit?

### ISSUE THREAD

**Issue by canha42** [canha42/pinterest-pin-it#14]
Plugin may be incompatible with Social Sharing Toolkit. I'll test this out.

Source:
http://wordpress.org/support/topic/plugin-pinterest-pin-it-button-for-images-latest-update-not-working?replies=5#post-3121221

Plugin:
http://www.active-bits.nl/support/social-sharing-toolkit/

**Comment by vhf** [comment]
`social-sharing-toolkit/includs/share.widget.php:29` :
`$output = preg_match_all('/<img.+src=[\'"]([^\'"]+)[\'"].*>/i', get_the_content(), $matches);`

Although we can be almost certain these two plugins are incompatible, further careful logging and debugging of how these two go along would be very useful.

**Comment by vhf** [comment]
All we can do is adding something like "Pinterest Pin It plugin can cause conflicts with other installed social plugins, such as Social Sharing Toolkit."

**Comment by canha42** [comment]
Ok. This will be done.
