### ISSUE TITLE
Exclude classes not precise enough

### ISSUE THREAD

**Issue by vhf** [canha42/pinterest-pin-it#15]
`preg_match( '/class=[\'"](.*)?' . trim( $pinthis ) . '(.*)?[\'"]/i', $tag, $matches );`
and
`preg_match( '/class=[\'"](.*)?' . trim( $class ) . '(.*)?[\'"]/i', $tag, $matches );`
in `ppibfi_pinterest.php` are buggy.

Suppose user wants to exclude images having class `nopin`. If image has class `hey-nopin-haha` or `nopinup` or `anopin` then image is excluded as well.

**Comment by vhf** [comment]
Fixed.

Benchmarks on 50k calls of each function : 

```
before              after
0.13801078796387    0.079992818832397
```

Previous function was really heavy.

**Comment by canha42** [comment]
Perfect!
