### ISSUE TITLE
"Don't show button on this post" doesn't work on index / home

### ISSUE THREAD

**Issue by canha42** [canha42/pinterest-pin-it#2]
When user selects the meta box (ppibfi_meta.php) to disable the "Pin It" button on a certain post, it works fine if the single post is viewed, but fails if the index/home is viewed. If there is one post with this option selected, all posts in index / home won't show the button.

Search ppibfi_pinterest.php for "Issue #2"

**Comment by pererinha** [comment]
About this issue I just uncommment the lines: 

``` php
  // Show on index.php / home page:
  if (get_option('ppibfi_pg_index') == "on" && is_home()) {
    ...
    if ($isOpted[0] != "on") {
      $content = pibfi_Engine_add_pin( $content, $pinterest_base_url, $post_url, $post_title );
     }
```

and it worked as well.
At the admin I checked the option Show "Pin It" button on following pages: Index / home
And also checked checked the option Opt-out on single pages: Enable opt-out
