### ISSUE TITLE
Error 502 when I click on the Pin it button

### ISSUE THREAD

**Issue by SophieAsselin** [canha42/pinterest-pin-it#21]
The Pin it button appears when I pass over the image. When I click, a new window opens. But when I click in the Pin it button in the new window, I have am error message 502. It's written : Oops! Our server is experiencing a mild case of the hiccups. We've reported it to the team.Try again?

Can you help me ?

You can see the Pin it button and my blog at this address : http://www.sophieasselin.com/blog/2012/11/le-grand-jour-de-laurence-et-francois/

Sophie

**Comment by vhf** [comment]
Sorry, this 502 error comes from Pinterest experiencing problems, most probably overload. If Pinterest is down, this plugin obviously won't work as expected. Thanks for the report anyway !

## 

Bonjour ! L'erreur est du côté de Pinterest, dont les serveurs semblent surchargés. Quand Pinterest rencontre ce type de problèmes techniques, il y a bien des risques que ce plugin puisse ne pas fonctionner comme annoncé. Merci quand même pour le rapport d'erreur !

**Comment by SophieAsselin** [comment]
I don't think so. I tried the same Pin it button on another photoblog, and it works ! It doesn't work only on MY photoblog. Help please !

In this website it works : http://www.carolinetran.net/blog/

In my website, it doesn't work : http://www.sophieasselin.com/blog

If I have a Prophoto blog, it suppose to work anyway ?

**Comment by vhf** [comment]
Yeah, no problem on any other prophoto blog. This error comes from Pinterest, and this is exactly what the error message says : "Our server is experiencing a mild case of the hiccups. We've reported it to the team."

Pinterest's servers are experiencing problems, and they reported the error to their technical staff. :)

**Comment by thisjustin** [comment]
From what I can tell this is a Pinterest issue and here's the cause - if you try to use the pin it button to share a link with a query string in it ( i.e. yoursite.com?foo=bar) pinterest will throw the 502 you're seeing. You would think you could just URL encode it (or more specifically in JS encodeURIComponent ) but even that doesn't work. So the only workaround I've found is to share a link that doesn't have a query sting in the URL, even if that means you do a redirect on your site to where you really want the link to go.
