### ISSUE TITLE
Add Author, Search and Archives

### ISSUE THREAD

**Issue by petekoromp** [canha42/pinterest-pin-it#36]
I was wondering how I could add the pin it button to author pages, search pages and archive pages.

Thanks

**Comment by chetmac** [comment]
Quick fix: Modify line 86 of the ppibfi_pinterest.php plugin file to look like:

elseif (get_option('ppibfi_pg_cat') == "on" && (is_category() || is_archive() || is_search() || is_author())) {

**Comment by canha42** [comment]
Thanks. Will include and test in next release!

**Comment by canha42** [comment]
Fixed. Will be available on 1.1
