### ISSUE TITLE
Pinterest button is redirecting to the parent anchor tag location.

### ISSUE THREAD

**Issue by ananthcampusoft** [canha42/pinterest-pin-it#37]
Hi

This is my code

<p style="text-align: center;"><a href="http://estatedevelopment.net/hairstyle/wp-content/uploads/2013/02/Color-One.png">
        <span class="pibfi_pinterest">
        <img width="285" height="404" src="http://estatedevelopment.net/hairstyle/wp-content/uploads/2013/02/Color-One.png" alt="Dark brown hair with red streak bangs and layered hair in a shag" title="Dark brown hair with red streak bangs and layered hair in a shag" class="aligncenter size-full wp-image-20318">
            <span onclick="pin_this(event, 'http://pinterest.com/pin/create/button/?url=http://estatedevelopment.net/hairstyle/reviews/organic-hair-dyes/&amp;media=http://estatedevelopment.net/hairstyle/wp-content/uploads/2013/02/Color-One.png&amp;description=Should You Go With Organic Hair Dyes?')" class="xc_pin" style="left: 162.5px; display: block;">
            </span>
        </span></a></p>

When i click this pin it button , it redirects to the parent anchor tag's location "http://estatedevelopment.net/hairstyle/wp-content/uploads/2013/02/Color-One.png" . 

Thanks in Advance. Please help me.

**Comment by canha42** [comment]
Should be fixed with new 1.1
