### ISSUE TITLE
Show only buttons on IMGs with certain CSS class

### ISSUE THREAD

**Issue by canha42** [canha42/pinterest-pin-it#4]
if the user selects to only show the button on IMGs with a certain class, the plugin will ignore all other images (even from Issue #3).

Search ppibfi_pinterest.php for "Issue #4"

**Comment by pererinha** [comment]
Solved. If the post has one or more images with the css class pinthis (pibfi_ShowButton), the Pin button'll be showed just for this(these) particular(s) images.
