### ISSUE TITLE
Button over post title

### ISSUE THREAD

**Issue by katme** [canha42/pinterest-pin-it#40]
I am having an issue where the button that should hover over the first image in my post is instead hovering over my post title. This means if you click on the post title it instead opens up the image link and obviously the pinit button is in the wrong place. Is there any way I can fix this? 
littlelabyrinth.com is where I am having the issue.

**Comment by canha42** [comment]
Not enough info / unable to reproduce. Maybe CSS conflict? Should be solved with 1.1.
