### ISSUE TITLE
pinit button not displaying by default

### ISSUE THREAD

**Issue by tillish** [canha42/pinterest-pin-it#42]
After installation, the pinit button doesn't display by default on images.  I can only get the pinit to display if I select "Show "Pin it" button only on images with "pinthis" class".  It would be better if I didn't have to go back and add classes to all of my existing images!

**Comment by canha42** [comment]
I see no reason why it shouldn't work, but I'll investigate.

**Comment by canha42** [comment]
Not enough info / not able to reproduce problem. Should be solved with 1.1.
