### ISSUE TITLE
pinit button not displaying on correct image when float is used

### ISSUE THREAD

**Issue by tillish** [canha42/pinterest-pin-it#43]
pinit button isn't displaying on the correct image when the float is used to style images in CSS.  for example: http://www.chantelbetts.com/vancouver-wedding-photography-queen-elizabeth-park/

**Comment by canha42** [comment]
When regular WordPress classes are used (alignleft, alignright, aligncenter, alignnone), the new 1.1 version should act accordingly. 

Unfortunately it's not possible to identify all other classes used, specially if they are non-WordPress specific. So, please stick to the WP-specific alignment classes and all should be dandy and mighty-fine!
