### ISSUE TITLE
pin it button not showing on featured image

### ISSUE THREAD

**Issue by imran1989** [canha42/pinterest-pin-it#46]
I have created a post and i have set a featured image but the pin button is not showing on this image why?

**Comment by canha42** [comment]
Will investigate.

**Comment by canha42** [comment]
Featured images are used in different way by different themes. Having the plugin work on all themes is an unrealistic approach. Unfortunately this isn't a feature that is feasible at the moment. Maybe in a far-from-now update, but still very unlikely. Sorry!
