### ISSUE TITLE
Pin It button doesn't appear when image doesn't have a filename/extension

### ISSUE THREAD

**Issue by eriksr** [canha42/pinterest-pin-it#49]
Here's what I mean -- check out this link, it is directly to a picture of a pitcher:

http://s7d9.scene7.com/is/image/BedBathandBeyond/19232718180227p?hei=730&wid=730

Note the lack of filename or file extension. The plugin doesn't recognize this as a picture and therefore doesn't display a Pin It button. Is there any workaround?

**Comment by canha42** [comment]
Will investigate to see if there is a workaround.

**Comment by canha42** [comment]
Regex must look for a file extension to work. If we change it to include anything, everything will have a Pin It button over it. Sorry, no workaround available at the moment and for foreseeable future.
