### ISSUE TITLE
Incomplete Title with Ampersands

### ISSUE THREAD

**Issue by purrdesign** [canha42/pinterest-pin-it#50]
Plugin isn't properly reading ampersands (&) in titles and will cut off the title at that point. Standard pinterest button and bookmarlet pull entire title, it's only this plugin that seems to have an issue with them.

Example:
http://www.loveandoliveoil.com/2013/09/toasted-almond-chocolate-granola.html

"Toasted Almond & Chocolate Granola" simply becomes "Toasted Almond"

**Comment by canha42** [comment]
Fixed & tested & available in next 1.1 :)
