### ISSUE TITLE
No button on custom post type

### ISSUE THREAD

**Issue by markorosic** [canha42/pinterest-pin-it#51]
Hi I'm using a custom "Brankic Bigbang" theme with custom post type for portfolio... I just installed the plugin, noticed that it only have single posts checkbox and buttons only show on blog posts but not images in portfolio.

Is there a workaround for this?

**Comment by canha42** [comment]
I'll investigate to see if it's something I can solve for the next major release (1.1)

**Comment by canha42** [comment]
Working with custom post types at this time is not possible. Sorry.
