### ISSUE TITLE
Pin it button isn't doing anything

### ISSUE THREAD

**Issue by totalnoms** [canha42/pinterest-pin-it#53]
I recently upgraded to WP 3.7, and while I'm not sure if that's the root cause or not, it appears as though the pin it button on my blog is no longer doing anything. When I hover on an image, the button appears, but nothing happens when I click on it. I've tried both Firefox and Chrome, running on a Mac.

My blog is totalnoms.com. Any help would be sincerely appreciated!

**Comment by canha42** [comment]
New 1.1 version working on WP 3.8.
