### ISSUE TITLE
Warning: Your maximum image width is thought to be 1024 pixels. This might be incorrect and might affect the functionality of the Pinterest Pin It plugin. Please check the plugins settings.

### ISSUE THREAD

**Issue by Rob12345** [canha42/pinterest-pin-it#54]
I don’t understand what this warning is supposed to tell me. The Pin It Button appears as expected and I seem to have no problems.

What is this warning message trying to tell me?
How can I make this warning go away?

Thank you very much.

**Comment by canha42** [comment]
Function removed. More pain then gain to keep it up. Will be available on 1.1
