### ISSUE TITLE
Pin it button stopped working

### ISSUE THREAD

**Issue by jamiekcc** [canha42/pinterest-pin-it#55]
Hi there, 
I had this successfully working for about 4 months. All of a sudden the last 2 posts aren't showing the pin it button. Can you help? 
www.kikicuisine.com

Thanks

**Comment by jamiekcc** [comment]
anyone? anyone?

**Comment by canha42** [comment]
I've checked the latest and oldest post. Seems to be working. Please provide a link to a specific post where problem arrises.

**Comment by canha42** [comment]
Update to 1.1.0. Official release was today.
