### ISSUE TITLE
disable button doesn't seem to work on images

### ISSUE THREAD

**Issue by davidlee221** [canha42/pinterest-pin-it#56]
When I'm trying to disable the image from showing, it says that the media attachment has updated, but then the button is deselected and no change is actually made.

**Comment by davidlee221** [comment]
I guess the workaround was just to add 'nopin' to the image tags.

**Comment by canha42** [comment]
Should be solved by v. 1.1

**Comment by davidlee221** [comment]
Thanks Sean, this thing is amazing by the way I forgot to mention.  Amazing!

On Fri, Jan 10, 2014 at 2:41 AM, Sean notifications@github.com wrote:

> Should be solved by v. 1.1
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/canha42/pinterest-pin-it/issues/56#issuecomment-32017594
> .

## 

_David Lee_
_c: 562-445-3000_ http://artofdavidlee.blogspot.com

**Comment by canha42** [comment]
Thanks! Glad you liked it!

Please consider donating any amount or sharing it on your social media 
pages!

Cheers,

## 

Sean Berg
(aka "Canha")
sean@canha.net mailto:sean@canha.net

> David Lee mailto:notifications@github.com
> 10 de janeiro de 2014 13:40
> Thanks Sean, this thing is amazing by the way I forgot to mention. 
> Amazing!
>
