### ISSUE TITLE
Pinterest plugin doesn't seem to be work

### ISSUE THREAD

**Issue by UniqueAbout** [canha42/pinterest-pin-it#57]
Hi, I'd really like to get this working, yet nothing seems to be happening. The current theme has an overlay when you mouseover the image in a blog post, which might be the issue. http://themeforest.net/item/camera-7-minimal-photography-wordpress-theme/full_screen_preview/6347984

The website is in maintenance mode, so I'd have to give you credentials through a secure place and need an email to create a user.

I'm really excited about this plugin and hope to get it working. Thanks.

**Comment by canha42** [comment]
Hi,
Try downloading and running the 1.1-nightly version (https://github.com/canha42/pinterest-pin-it/tree/1.1-nightly) and let me know if it works.

**Comment by UniqueAbout** [comment]
I'm not sure what you mean.

Thanks.

**Comment by canha42** [comment]
Ok, let's try and make this simple LOL
- Go to: https://github.com/canha42/pinterest-pin-it/tree/1.1-nightly
- Find download button. Click. Save file to computer
- Go to your WordPress. Plugins menu. Disable the current "Pinterest" plugin you have installed. Click on "add new", find "upload" link on top of page. Select previously downloaded file. Activate.
- Let me know if this works!

**Comment by canha42** [comment]
Try updating your plugin thru WordPress. New 1.1.0 version was released today.
