### ISSUE TITLE
Ability to have button always visible

### ISSUE THREAD

**Issue by canha42** [canha42/pinterest-pin-it#6]
Option in the settings window to always have the "Pin It" button always visible - should still obey other rules set by the user (exclude certain tags, only show on certain tags, page/post opt-out).

**Comment by JerseyAl** [comment]
Would love to see this in conjunction with being able to change the size of the pinit button...

**Comment by scalablesocial** [comment]
Yes,I would like this as well.

**Comment by canha42** [comment]
At the moment, can be changed via CSS. But an interface option will only be added in a future version.
