### ISSUE TITLE
Ability to change description

### ISSUE THREAD

**Issue by canha42** [canha42/pinterest-pin-it#7]
Add an option to change the description that is sent to Pinterest:
- Standard description (one for all images)
- Title of post only
- Title of post + post link
- Link post only
- Website link + name
- Website name + post name + post link
- Blank

**Comment by JerseyAl** [comment]
This would be a great enhancement to the plugin. Would love to see this.

**Comment by scalablesocial** [comment]
Me, too!

**Comment by blaskotron** [comment]
+1. Should be showing the image description instead of post title.
