### ISSUE TITLE
Ability to change Pin It button

### ISSUE THREAD

**Issue by canha42** [canha42/pinterest-pin-it#8]
Create an option in the settings page to upload a "Pin It" button.

After the upload is complete, the script must detect the height and width of this button. This information will be added as CSS, so the jQuery can easily detect where the button will be placed. The URL of the button also will be added to the CSS as background-image.

Class that needs to be altered:
.xc_pin { }

**Comment by vhf** [comment]
Done. Please conduct some tests, report bugs and/or fix them.

**Comment by canha42** [comment]
Testing. Will post results shortly.

**Comment by vhf** [comment]
Okay, now it should work. Fixed several issues.

Looks like WP's default URL routing doesn't allow PHP acting as CSS. (Interesting article on this matter : http://josephscott.org/archives/2010/03/database-powered-css-in-wordpress-themes/ )

Keep me updated

**Comment by canha42** [comment]
Great. I was swamped last weekend, will give a look today ;)

**Comment by canha42** [comment]
I can't get the button to work. As soon as I click it, it 404's me (the thickbox loads, but the media uploader doesn't show). If I access the media uploader file directly, it goes. But now within the plugin. Can you check this for me?

**Comment by vhf** [comment]
Well, this issue should only occurs offline, and it seems we cannot get around it...

Try the plugin somewhere on-line, you'll see that it works. As of why it 404's when working offline, it seems that nobody knows...

**Comment by canha42** [comment]
This won't be fixed just yet. User can change the CSS style, but won't have an interface at the moment. Maybe in a future version.
